# Generated by Django 4.2 on 2024-10-06 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("matricula", "0002_rename_correo_representante_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="representante",
            name="cedula",
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name="representante",
            name="nombre",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name="representante",
            name="telefono",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
