# Generated by Django 4.2 on 2024-10-06 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("matricula", "0003_alter_representante_cedula_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="programa",
            name="agrupacion",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="matricula.agrupacion",
            ),
        ),
        migrations.AlterField(
            model_name="representante",
            name="parentesco",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
