# Generated by Django 4.2 on 2024-10-06 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("matricula", "0004_alter_programa_agrupacion_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="programa",
            name="agrupacion",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="matricula.agrupacion",
            ),
        ),
    ]
