# Generated by Django 4.2.16 on 2024-11-08 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matricula', '0011_alumno_condicion_especial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='catedras',
            field=models.ManyToManyField(blank=True, to='matricula.catedra'),
        ),
    ]
