# Generated by Django 4.2 on 2024-11-08 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matricula', '0013_remove_programa_agrupacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='agrupacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='matricula.agrupacion'),
        ),
    ]
