# Generated by Django 4.2 on 2024-11-15 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("matricula", "0014_alumno_agrupacion"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="agrupacion",
            name="instrumentos",
        ),
        migrations.RemoveField(
            model_name="alumno",
            name="instrumentos",
        ),
        migrations.RemoveField(
            model_name="catedra",
            name="instrumento",
        ),
        migrations.AddField(
            model_name="instrumento",
            name="alumno",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="matricula.alumno",
            ),
        ),
    ]
