# Generated by Django 4.2.16 on 2024-11-23 22:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matricula', '0015_remove_agrupacion_instrumentos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='direccion',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='sexo',
            field=models.CharField(choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino'), ('Otro', 'Otro')], max_length=32),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='telefono',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='instrumento',
            name='alumno',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instrumentos', to='matricula.alumno'),
        ),
        migrations.AlterField(
            model_name='instrumento',
            name='asignado',
            field=models.CharField(blank=True, choices=[('Asignado', 'Asignado'), ('Propio', 'Propio')], max_length=128, null=True),
        ),
    ]
